// Bilingual copy. {var} placeholders are filled by t(key, vars).
export const copy = {
  en: {
    'ui.lang': '中',
    'ui.brand': 'Year in Review 2025',
    'ui.continue': 'Continue',
    'ui.tap': 'Tap to continue',
    'ui.thinking': 'Thinking',
    'ui.thought': 'Thought for {s}s',
    'ui.running': 'running',
    'ui.done': 'done',
    'ui.accepted': 'Accepted',
    'ui.declined': 'Declined',
    'ui.status.idle': 'okx-trade-mcp · idle',
    'ui.status.connecting': 'okx-trade-mcp · connecting…',
    'ui.status.live': 'okx-trade-mcp · connected · read-only',
    'ui.status.working': 'agent is working…',
    'ui.followup': 'Ask a follow-up…',
    'ui.skills': 'Skills',
    'ui.process': 'Process',
    'ui.collapse': 'Collapse',
    'ui.new': 'NEW',

    'cover.eyebrow': 'OKX AGENT · YEAR IN REVIEW',
    'cover.title': 'TRADING BLUEPRINT',
    'cover.sub': 'Decode your patterns of growth',
    'cover.hint': 'Type / to pick a skill, then ask for your 2025 report',

    'composer.placeholder': 'Ask your agent anything…',
    'skills.group': 'OKX Agent Trade Kit · MCP',
    'skills.okx-year-in-review': 'Your 2025 trading blueprint',
    'skills.okx-cex-portfolio': 'Balances, positions, history',
    'skills.okx-cex-market': 'Tickers, candles, indicators',
    'skills.okx-cex-trade': 'Spot & futures orders',
    'skills.okx-cex-bot': 'Grid & DCA bots',
    'skills.okx-cex-earn': 'Yield products',
    'skills.okx-cex-smartmoney': 'Trader analytics',

    'user.prompt': 'Show me my 2025 annual report',

    'ch1.think': [
      'Loading skill okx-year-in-review',
      'Connecting okx-trade-mcp over stdio',
      '167 tools across 11 modules discovered',
      'Scoping to read-only account & history tools',
    ],

    'session.ready': 'Connected, read-only. Replaying your 2025 records one tool call at a time — nothing leaves this device.',

    'ch2.name': 'GENESIS',
    'ch2.think': ['Fetching account profile', 'Reading registration timestamp', 'Computing tenure through Dec 31, 2025'],
    'ch2.b1': 'Let me start at the beginning. Your account came online on {date}.',
    'ch2.b2': 'That’s {days} days on the same frequency — {years}+ years of showing up, cycle after cycle.',
    'ch2.b3': 'Since {date}, you’ve been our constant. Now let’s see what 2025 added to the story.',
    'ch2.label': 'days together',
    'ch2.since': 'since {date}',

    'ch3.name': 'FIRST SIGNAL',
    'ch3.think': ['Scanning spot fills from Jan 1, 00:00', 'Sorting by fill time', 'Locating the first executed order'],
    'ch3.b1': '2025 began early for you — at {time} on New Year’s Day.',
    'ch3.b2': 'Your first order of the year: BUY {sz} BTC at {px} USDT. Spot, filled instantly.',
    'ch3.b3': 'You planted this year’s first seed with BTC. Every blueprint starts with a single line.',
    'ch3.receipt': 'FILLED',

    'ch4.name': 'ACTIVITY',
    'ch4.think': ['Pulling 12 months of bills', 'Aggregating activity by day', 'Ranking pairs and tokens by notional'],
    'ch4.b1': 'I scanned all 365 days of your bills. This is your year as a grid — the brighter the cell, the busier the day.',
    'ch4.b2': 'You showed up on {days} of them and completed {trades} trades. Consistency like that is rare.',
    'ch4.b3': '{pair} was your most traded pair, and {token} the largest token in your flow.',
    'ch4.days': 'active days',
    'ch4.trades': 'trades',
    'ch4.pair': 'most traded pair',
    'ch4.token': 'largest token',

    'ch5.name': 'BEST TRADE',
    'ch5.think': ['Rebuilding realised PnL fill by fill', 'Sorting by single-trade profit', 'Isolating the best one'],
    'ch5.b1': 'Here’s your realised PnL compounding across the year — a staircase, not a rocket.',
    'ch5.b2': 'The steepest step landed on {date}: {inst} {market}, +{pnl} USDT in a single trade.',
    'ch5.b3': 'One clean signal, perfectly executed. That’s your best trade of 2025.',
    'ch5.label': 'realised on {date}',
    'ch5.curve': 'Cumulative realised PnL · 2025',

    'ch6.name': 'HARVEST',
    'ch6.think': ['Summing realised + unrealised PnL', 'Dividing by average deployed capital', 'Benchmarking against all OKX traders'],
    'ch6.b1': 'Add it all up: you earned {total} USDT in 2025.',
    'ch6.b2': 'That’s a yield of {pct}% on your capital.',
    'ch6.b3': 'Better than {beats}% of all traders on OKX. A harvest worth pausing on.',
    'ch6.label': 'earned in 2025',
    'ch6.yield': 'yield',
    'ch6.beats': 'Better than {beats}% of traders',
    'ch6.you': 'YOU',

    'choice.eyebrow': 'YOUR CALL',
    'choice.q': 'Where should I dig in next?',
    'choice.volume': 'Trading volume',
    'choice.earn': 'Earn',
    'choice.bots': 'Trading bots',
    'choice.ack': 'Good call. Pulling {what} first.',

    'ch7.name': 'VOLUME',
    'ch7.think': ['Summing notional across venues', 'Splitting spot / futures / DEX', 'Checking the ranking'],
    'ch7.b1': 'Your notional volume grew to {total} USDT across the year.',
    'ch7.b2': 'Spot led the way at {spot}, then futures at {futures}, then on-chain DEX at {dex}.',
    'ch7.b3': 'Three venues, one blueprint. You kept most of your weight in spot — patient capital.',
    'ch7.label': 'USDT traded',
    'ch7.spot': 'Spot',
    'ch7.futures': 'Futures',
    'ch7.dex': 'DEX',

    'ch8.name': 'EARN',
    'ch8.think': ['Reading Earn subscriptions', 'Replaying daily reward accruals', 'Netting rewards to year end'],
    'ch8.b1': 'With Earn, you subscribed {sub} USDT to {product}.',
    'ch8.b2': 'It kept accruing while you slept — {earned} USDT in rewards by year end.',
    'ch8.b3': 'Passive doesn’t mean idle. That’s {pct}% on the capital you parked.',
    'ch8.sub': 'subscribed',
    'ch8.earned': 'earned',
    'ch8.accrual': 'Reward accrual',

    'ch9.name': 'BOTS',
    'ch9.think': ['Loading bot order history', 'Replaying grid fills level by level', 'Attributing profit per grid'],
    'ch9.b1': 'Your Spot grid bot worked the range — buying the dips, selling the rips, on a schedule, across {trades} fills.',
    'ch9.b2': 'On {vol} USDT of bot volume, it earned you {earned} USDT.',
    'ch9.b3': 'Your Spot grid formula worked perfectly — less stress, more stability.',
    'ch9.label': 'earned by bots',
    'ch9.trades': 'bot trades',
    'ch9.vol': 'volume',
    'ch9.buy': 'Grid buy',
    'ch9.sell': 'Grid sell',

    'ch10.name': 'PEAK',
    'ch10.think': ['Valuing assets day by day', 'Marking to USDT at daily close', 'Locating the all-time high'],
    'ch10.b1': 'I valued your portfolio day by day. Here’s the whole curve.',
    'ch10.b2': 'It peaked on {date} at {value} USDT — your all-time high.',
    'ch10.b3': 'Not just a personal best. That’s top {pct}% territory across OKX.',
    'ch10.label': 'peak valuation',
    'ch10.top': 'TOP {pct}%',
    'ch10.curve': 'Total asset value · 2025',

    'ch11.name': 'FLOW',
    'ch11.think': ['Listing deposits and withdrawals', 'Netting the two flows', 'Checking capital retention'],
    'ch11.b1': 'Money in: you deposited {dep} USDT over the year.',
    'ch11.b2': 'Money out: you withdrew {wd} USDT.',
    'ch11.b3': '{net} USDT stayed at work on OKX. You mastered the flow — capital in balance.',
    'ch11.in': 'Deposited',
    'ch11.out': 'Withdrawn',
    'ch11.net': 'retained on OKX',

    'ch12.name': 'TRADING DNA',
    'ch12.think': ['Scoring 5 behavioural signals', 'Normalising against your cohort', 'Plotting the profile'],
    'ch12.b1': 'From everything above I scored five behavioural signals. This is your trading DNA.',
    'ch12.b2': 'Automation ({automation}) and consistency ({consistency}) run hot. Risk control holds at {risk}.',
    'ch12.b3': 'Diversity sits lower at {diversity} — you know your lane. That’s a pattern I recognise.',
    'radar.automation': 'Automation',
    'radar.consistency': 'Consistency',
    'radar.yield': 'Yield',
    'radar.risk': 'Risk control',
    'radar.diversity': 'Diversity',

    'ch13.name': 'PERSONA',
    'ch13.analyzing': 'Analyzing your blueprint…',
    'ch13.think': ['Correlating 5 behavioural signals', 'Matching against 12 trader archetypes', 'Confidence 0.94 → archetype locked'],
    'mint.title': 'Mint your 2025 persona card?',
    'mint.body': 'I’ll render a shareable card from your blueprint. Nothing is uploaded.',
    'mint.accept': 'Mint it',
    'mint.later': 'Not now',
    'mint.done': 'Card minted',
    'mint.skipped': 'Skipped for now',
    'mint.declined': 'No problem — your blueprint is complete either way. The card is one tap away whenever you want it.',
    'ch13.b1': 'Blueprint decoded. You are {persona}.',
    'ch13.b2': '{tagline}',
    'ch13.closing': 'That’s your 2025. Same tools, your own agent — the kit is open source. Ask me anything else about your year.',

    'persona.gridArchitect.name': 'THE GRID ARCHITECT',
    'persona.gridArchitect.tag': 'You don’t chase candles. You build the structure they fall into.',
    'persona.gridArchitect.traits': ['Automation-first', 'Steady hands', 'Compounding mindset'],
    'persona.alphaHarvester.name': 'THE ALPHA HARVESTER',
    'persona.alphaHarvester.tag': 'You read the field, then you reap it.',
    'persona.alphaHarvester.traits': ['Yield-driven', 'Timing', 'Patience'],
    'persona.steadyCompounder.name': 'THE STEADY COMPOUNDER',
    'persona.steadyCompounder.tag': 'Every day counts. You showed up for 315 of them.',
    'persona.steadyCompounder.traits': ['Consistency', 'Discipline', 'Long game'],
    'persona.explorer.name': 'THE EXPLORER',
    'persona.explorer.tag': 'Spot, futures, on-chain — you map every frontier.',
    'persona.explorer.traits': ['Curious', 'Diversified', 'Early'],
    'persona.sentinel.name': 'THE RISK SENTINEL',
    'persona.sentinel.tag': 'You protect the downside so the upside can breathe.',
    'persona.sentinel.traits': ['Risk-aware', 'Measured', 'Resilient'],

    'card.title': '2025 · YEAR IN REVIEW',
    'card.earned': 'Earned',
    'card.yield': 'Yield',
    'card.days': 'Active days',
    'card.trades': 'Trades',
    'card.volume': 'Volume',
    'card.peak': 'Peak assets',

    'cta.title': 'Bring OKX into your own agent',
    'cta.body': 'This report ran on the same tools. API, MCP or Skills — your call.',
    'cta.copy': 'Copy',
    'cta.copied': 'Copied',
    'cta.save': 'Save card',
    'cta.replay': 'Replay',
    'cta.repo': 'github.com/okx/agent-trade-kit',
    'sheet.hint': 'Long-press the image to save · or',
    'sheet.download': 'Download PNG',
    'sheet.close': 'Close',
    'followup.reply': 'This demo agent only knows your 2025 blueprint. For live balances, orders and bots, plug okx-trade-mcp into your own agent — the link is right above.',
  },

  zh: {
    'ui.lang': 'EN',
    'ui.brand': '2025 年度账单',
    'ui.continue': '继续',
    'ui.tap': '点击继续',
    'ui.thinking': '思考中',
    'ui.thought': '思考了 {s} 秒',
    'ui.running': '执行中',
    'ui.done': '完成',
    'ui.accepted': '已授权',
    'ui.declined': '已拒绝',
    'ui.status.idle': 'okx-trade-mcp · 空闲',
    'ui.status.connecting': 'okx-trade-mcp · 连接中…',
    'ui.status.live': 'okx-trade-mcp · 已连接 · 只读',
    'ui.status.working': '智能体正在执行…',
    'ui.followup': '继续追问…',
    'ui.skills': '技能',
    'ui.process': '过程',
    'ui.collapse': '收起',
    'ui.new': '新',

    'cover.eyebrow': 'OKX AGENT · 年度账单',
    'cover.title': 'TRADING BLUEPRINT',
    'cover.sub': '解码你的成长轨迹',
    'cover.hint': '输入 / 选择技能，然后向智能体索要你的 2025 账单',

    'composer.placeholder': '问智能体任何问题…',
    'skills.group': 'OKX Agent Trade Kit · MCP',
    'skills.okx-year-in-review': '你的 2025 交易蓝图',
    'skills.okx-cex-portfolio': '余额、持仓、历史',
    'skills.okx-cex-market': '行情、K 线、指标',
    'skills.okx-cex-trade': '现货与合约下单',
    'skills.okx-cex-bot': '网格与定投机器人',
    'skills.okx-cex-earn': '赚币产品',
    'skills.okx-cex-smartmoney': '聪明钱分析',

    'user.prompt': '看看我的 2025 年度账单',

    'ch1.think': ['加载技能 okx-year-in-review', '通过 stdio 连接 okx-trade-mcp', '发现 11 个模块共 167 个工具', '限定为只读的账户与历史工具'],

    'session.ready': '已连接，只读模式。开始逐个调用工具，回放你的 2025——数据不会离开这台设备。',

    'ch2.name': '起点',
    'ch2.think': ['读取账户档案', '解析注册时间戳', '计算到 2025 年 12 月 31 日的时长'],
    'ch2.b1': '让我从最开始说起。你的账户在 {date} 上线。',
    'ch2.b2': '到今天是 {days} 天，同一个频率——{years} 年多，一个周期又一个周期，你都在。',
    'ch2.b3': '自 {date} 起，你一直在这里。现在，看看 2025 为这个故事添了什么。',
    'ch2.label': '天 · 与 OKX 同行',
    'ch2.since': '自 {date}',

    'ch3.name': '首笔信号',
    'ch3.think': ['扫描 1 月 1 日 00:00 起的现货成交', '按成交时间排序', '定位年内第一笔成交'],
    'ch3.b1': '你的 2025 开始得很早——元旦当晚 {time}。',
    'ch3.b2': '今年第一笔订单：以 {px} USDT 买入 {sz} BTC。现货，即时成交。',
    'ch3.b3': '你用 BTC 种下了今年的第一颗种子。每一张蓝图，都始于第一条线。',
    'ch3.receipt': '已成交',

    'ch4.name': '活跃度',
    'ch4.think': ['拉取 12 个月账单', '按天聚合活跃度', '按名义金额为交易对与代币排序'],
    'ch4.b1': '我扫描了你全年 365 天的账单。这是把你的一年铺成格子的样子——格子越亮，那天越忙。',
    'ch4.b2': '其中 {days} 天你都在场，完成了 {trades} 笔交易。这样的稳定，并不常见。',
    'ch4.b3': '{pair} 是你交易最多的币对，{token} 是你资金流中最大的代币。',
    'ch4.days': '活跃天数',
    'ch4.trades': '笔交易',
    'ch4.pair': '最常交易币对',
    'ch4.token': '最大交易代币',

    'ch5.name': '最佳交易',
    'ch5.think': ['逐笔重建已实现盈亏', '按单笔利润排序', '锁定最佳的那一笔'],
    'ch5.b1': '这是你全年的已实现盈亏曲线——像楼梯，而不是火箭。',
    'ch5.b2': '最陡的一级台阶出现在 {date}：{inst} {market}，单笔 +{pnl} USDT。',
    'ch5.b3': '一次干净的信号，完美执行。这就是你 2025 的最佳交易。',
    'ch5.label': '{date} 实现',
    'ch5.curve': '累计已实现盈亏 · 2025',

    'ch6.name': '收获',
    'ch6.think': ['汇总已实现与未实现盈亏', '除以平均投入资金', '与全体 OKX 用户对比'],
    'ch6.b1': '把这一切加起来：2025 年你赚了 {total} USDT。',
    'ch6.b2': '相当于 {pct}% 的资金收益率。',
    'ch6.b3': '超过了 {beats}% 的 OKX 用户。这份收获，值得停下来看一眼。',
    'ch6.label': '2025 年收益',
    'ch6.yield': '收益率',
    'ch6.beats': '超过 {beats}% 的用户',
    'ch6.you': '你',

    'choice.eyebrow': '由你决定',
    'choice.q': '接下来先看哪一项？',
    'choice.volume': '交易量',
    'choice.earn': '赚币',
    'choice.bots': '策略机器人',
    'choice.ack': '好，先拉取{what}。',

    'ch7.name': '交易量',
    'ch7.think': ['汇总各场景名义交易额', '拆分现货 / 合约 / DEX', '核对排名'],
    'ch7.b1': '全年下来，你的名义交易量增长到 {total} USDT。',
    'ch7.b2': '现货领跑，{spot}；合约其次，{futures}；链上 DEX 为 {dex}。',
    'ch7.b3': '三个场景，一张蓝图。你把大部分重量放在现货——耐心的资金。',
    'ch7.label': 'USDT 交易量',
    'ch7.spot': '现货',
    'ch7.futures': '合约',
    'ch7.dex': 'DEX',

    'ch8.name': '赚币',
    'ch8.think': ['读取赚币申购记录', '回放每日收益累计', '结算到年末'],
    'ch8.b1': '在赚币里，你申购了 {sub} USDT 的 {product}。',
    'ch8.b2': '它在你睡觉时持续计息——到年底累计 {earned} USDT 收益。',
    'ch8.b3': '被动不等于闲置。这笔停在那里的钱，回报了 {pct}%。',
    'ch8.sub': '申购',
    'ch8.earned': '收益',
    'ch8.accrual': '收益累计',

    'ch9.name': '策略机器人',
    'ch9.think': ['加载机器人订单历史', '逐层回放网格成交', '按网格归因利润'],
    'ch9.b1': '你的现货网格机器人在区间里来回工作——跌了买、涨了卖，按节奏执行了 {trades} 笔成交。',
    'ch9.b2': '在 {vol} USDT 的机器人交易量上，为你赚到 {earned} USDT。',
    'ch9.b3': '现货网格公式运转完美：更少焦虑，更多稳定。',
    'ch9.label': '机器人收益',
    'ch9.trades': '笔机器人交易',
    'ch9.vol': '交易量',
    'ch9.buy': '网格买入',
    'ch9.sell': '网格卖出',

    'ch10.name': '峰值',
    'ch10.think': ['逐日估值资产', '按每日收盘折算为 USDT', '定位年内最高点'],
    'ch10.b1': '我逐日给你的资产估了值。这是完整的一条曲线。',
    'ch10.b2': '它在 {date} 达到峰值 {value} USDT——你的历史新高。',
    'ch10.b3': '不只是个人最佳。在全体 OKX 用户里，这是前 {pct}% 的领域。',
    'ch10.label': '资产峰值',
    'ch10.top': '前 {pct}%',
    'ch10.curve': '总资产估值 · 2025',

    'ch11.name': '资金流',
    'ch11.think': ['列出全年充值与提现', '计算两股流的净额', '检查资金留存'],
    'ch11.b1': '进：全年你充值了 {dep} USDT。',
    'ch11.b2': '出：你提现了 {wd} USDT。',
    'ch11.b3': '{net} USDT 留在 OKX 继续工作。你掌控着资金的流向，让它保持平衡。',
    'ch11.in': '充值',
    'ch11.out': '提现',
    'ch11.net': '留存在 OKX',

    'ch12.name': '交易 DNA',
    'ch12.think': ['为 5 项行为信号打分', '与同类用户归一化对比', '绘制画像'],
    'ch12.b1': '基于上面的一切，我给你的五项行为信号打了分。这就是你的交易 DNA。',
    'ch12.b2': '自动化（{automation}）和稳定性（{consistency}）格外突出，风控稳在 {risk}。',
    'ch12.b3': '多样性略低，{diversity}——你清楚自己的赛道。这是我认得的模式。',
    'radar.automation': '自动化',
    'radar.consistency': '稳定性',
    'radar.yield': '收益',
    'radar.risk': '风控',
    'radar.diversity': '多样性',

    'ch13.name': '人格',
    'ch13.analyzing': '正在解析你的蓝图…',
    'ch13.think': ['关联 5 项行为信号', '匹配 12 种交易者原型', '置信度 0.94 → 原型锁定'],
    'mint.title': '生成你的 2025 人格卡片？',
    'mint.body': '我会根据你的蓝图渲染一张可分享的卡片，不会上传任何数据。',
    'mint.accept': '生成',
    'mint.later': '暂不',
    'mint.done': '卡片已生成',
    'mint.skipped': '暂未生成',
    'mint.declined': '没问题，你的蓝图已经完成。想要卡片时随时点一下。',
    'ch13.b1': '蓝图解码完成。你是{persona}。',
    'ch13.b2': '{tagline}',
    'ch13.closing': '这就是你的 2025。同样的工具，你自己的智能体，工具包完全开源。还想了解这一年的什么，尽管问我。',

    'persona.gridArchitect.name': '网格建筑师',
    'persona.gridArchitect.tag': '你不追逐 K 线，你搭建让它们落入的结构。',
    'persona.gridArchitect.traits': ['自动化优先', '稳如磐石', '复利思维'],
    'persona.alphaHarvester.name': 'Alpha 收割者',
    'persona.alphaHarvester.tag': '你读懂场地，然后收割它。',
    'persona.alphaHarvester.traits': ['收益导向', '择时', '耐心'],
    'persona.steadyCompounder.name': '稳健复利者',
    'persona.steadyCompounder.tag': '每一天都算数，你出现了 315 天。',
    'persona.steadyCompounder.traits': ['稳定', '自律', '长期主义'],
    'persona.explorer.name': '探索者',
    'persona.explorer.tag': '现货、合约、链上，你绘制每一片疆域。',
    'persona.explorer.traits': ['好奇', '多元', '早鸟'],
    'persona.sentinel.name': '风控哨兵',
    'persona.sentinel.tag': '你守住下行，让上行自由呼吸。',
    'persona.sentinel.traits': ['风险意识', '克制', '韧性'],

    'card.title': '2025 · 年度账单',
    'card.earned': '收益',
    'card.yield': '收益率',
    'card.days': '活跃天数',
    'card.trades': '交易笔数',
    'card.volume': '交易量',
    'card.peak': '资产峰值',

    'cta.title': '把 OKX 接进你自己的智能体',
    'cta.body': '这份账单就跑在同一套工具上。API、MCP 或 Skills，任你选择。',
    'cta.copy': '复制',
    'cta.copied': '已复制',
    'cta.save': '保存卡片',
    'cta.replay': '重播',
    'cta.repo': 'github.com/okx/agent-trade-kit',
    'sheet.hint': '长按图片保存 · 或',
    'sheet.download': '下载 PNG',
    'sheet.close': '关闭',
    'followup.reply': '这个演示智能体只了解你的 2025 蓝图。要查看实时余额、订单和机器人，把 okx-trade-mcp 接入你自己的智能体即可，链接就在上方。',
  },
};

export const SKILLS = [
  { id: 'okx-year-in-review', badge: true },
  { id: 'okx-cex-portfolio' },
  { id: 'okx-cex-market' },
  { id: 'okx-cex-trade' },
  { id: 'okx-cex-bot' },
  { id: 'okx-cex-earn' },
  { id: 'okx-cex-smartmoney' },
];
